### PR TITLE
Update to latest upstream master

### PR DESCRIPTION
**Pull request by Aaron1011**
This pulls in a fix for https://github.com/ianlancetaylor/libbacktrace/issues/32

### CODE REVIEW

**Comment by alexcrichton** [comment]
I don't believe the master branch of this repository is used, but rather the `rust-snapshot-*` branch is used by the backtrace crate.

**Comment by ghost** [comment]
Rebasing on upstream would also fix https://github.com/rust-lang/rust/issues/54434 which would be nice to see happen.

**Comment by Aaron1011** [comment]
@alexcrichton: Should I make a pull request merging upstream into `rust-snapshot-2018-05-22`, or should someone make a newer `rust-snapshot` branches with the fixes from `rust-snapshot-2018-05-22` applied?

**Comment by alexcrichton** [comment]
@Aaron1011 I think the best thing to do is to make a new branch based of libbacktrace's master branch, then cherry-pick all the Rust fixes, then show me where the branch is so I can push it up to this repository

**Comment by ghost** [comment]
@alexcrichton I have done that here: https://github.com/t6/libbacktrace/tree/rust-snapshot-2020-02-19

I did not really know what to do with the preliminary macho support upstream added. Reading https://github.com/ianlancetaylor/libbacktrace/pull/2#issuecomment-588010400 I'm not convinced it is ready so I reverted that commit.

**Comment by alexcrichton** [comment]
Thanks @t6! Mind sending a PR to the `backtrace` crate with this submodule update? That should run CI and see if everything still works, and when that's all ship shape I can push the branch up to this repo.

One worry I'd have is that we do rely on mach-o support in one form or another, but so long as all the tests are passing I think it's fine.

**Comment by ghost** [comment]
https://github.com/rust-lang/backtrace-rs/pull/299

**Comment by alexcrichton** [comment]
This is now a branch at https://github.com/rust-lang/libbacktrace/tree/rust-snapshot-2020-02-19, so closing.

**Pull request closed without merging**
