### PR TITLE
update "config.guess" and "config.sub"

### PR DESCRIPTION
**Pull request by stefantalpalaru**
...to latest versions from "http://git.savannah.gnu.org/cgit/config.git/tree/".

An old "i" prefix in "i*:MSYS*:*)" was preventing the library from
being built in AppVeyor CI jobs.

Also  update ".gitignore" with generic Autotools entries and a specific one for a generated
header. This allows building the project in the same directory as the source.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I don't think that this is used by any Rust build bits any more, so can you clarify on what this would fix?

**Comment by stefantalpalaru** [comment]
I'm using it for https://github.com/status-im/nim-libbacktrace

**Comment by alexcrichton** [comment]
Ah ok thanks for clarifying, but this fork of libbacktrace isn't intended to be used for anything other than the `backtrace` crate in Rust, and I at least personally don't have the time to maintain it for other uses unfortunately.

**Comment by stefantalpalaru** [comment]
OK, I'll fork the fork :-)

**Pull request closed without merging**
